# This workflow build all the Rust projects contained in this monorepo.

---
on: [push]

name: CI

jobs:
  build:
    name: Build Rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build projects
        run: sh ./scripts/ci.sh
